### ISSUE TITLE
Permissions issue (using compose)

### ISSUE THREAD

**Issue by bddenhartog** [nginxinc/docker-nginx#113]
A simple compose configuration leaves my static files owned by the UID of my host user, and inaccessible to the nginx process.

```yaml
nginx:
    image: nginx:stable-alpine
    volumes:
        - ./app:/usr/share/nginx/html
    ports:
        - '80:80'
        - '443:443'
```

The directory inside the container is, in this case, owned by `1000`, which is the user's ID from my host machine. `./app/` simply contains a single `index.html` file.

I don't see any options in [the documentation](https://github.com/docker-library/docs/tree/master/nginx) that cover permissions. Is there an environment variable I can submit to the container during build to change the UID of the www-data user?
