### ISSUE TITLE
Address already in use?

### ISSUE THREAD

**Issue by KevinBurton** [nginxinc/docker-nginx#220]
I have a very simple docker-compose file
```
nginx:
    build: ./nginx
    links:
        - node1:node1
        - node2:node2
        - node3:node3
    ports:
        - "80:80"
node1:
    build: ./node
    links:
        - redis
    ports:
        - "8080"
node2:
    build: ./node
    links:
        - redis
    ports:
        - "8080"
node3:
    build: ./node
    links:
        - redis
    ports:
        - "8080"
redis:
    image: redis
    ports:
        - "6379"
```
When I do docker-compose up I get:

`ERROR: for d1877a6fa959_d1877a6fa959_dockerworkflow_nginx_1  Cannot start service nginx: driver failed programming external connectivity on endpoint d1877a6fa959_d1877a6fa959_dockerworkflow_nginx_1 (575d6f4790a9b8dd205625937f495e8569ec5390039e186e6ea26d4a935f0ed3): Error starting userland proxy: Bind for 0.0.0.0:80: unexpected error (Failure EADDRINUSE)`

I am on a MAC is there something that I am missing?

Thank you.

Kevin
