### ISSUE TITLE
.conf file is considered as directory

### ISSUE THREAD

**Issue by alexchitoraga** [nginxinc/docker-nginx#241]
On running docker compose I've got an error about .conf file which is considered as directory.

![image](https://user-images.githubusercontent.com/7384488/38725181-2de4d10c-3f0f-11e8-8804-eb7932cb67eb.png)

Configuration for docker-compose.yml is next:
```
nginx:
        image: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./conf/nginx/frontend.conf:/etc/nginx/conf.d/frontend.conf
            - ./frontend/public:/var/www/frontend/public
            - ./admin/public:/var/www/admin/public
            - ./conf/ssl:/etc/nginx/ssl
        depends_on:
            - frontend
            - admin
```

Docker versions:
![image](https://user-images.githubusercontent.com/7384488/38725269-77124404-3f0f-11e8-91ae-6e795cf220b6.png)

Problem is that sometimes it's works and sometimes no. Now it's not working at all.
