### ISSUE TITLE
[Support] Can't set directives out of the http context

### ISSUE THREAD

**Issue by Frondor** [nginxinc/docker-nginx#247]
This is not an issue for sure, but I'm a newbie and found some problems when trying to use this image.

Basically, I want to use the `nginx-app.template` approach based on what's written in the docs:

```yml
  nginx:
    container_name: webserver
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    depends_on:
      - restful_api
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_PORT=80
    volumes:
      - ./nginx/nginx-app.template:/etc/nginx/conf.d/nginx-app.template
      - ./nginx/certs:/etc/ssl/certs
    command: /bin/sh -c "envsubst '$$NGINX_PORT' < /etc/nginx/conf.d/nginx-app.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: unless-stopped
```

but if I want to set something like `worker_processes` or such directives, it's not possible because it seems to be included inside the `http` context of `/etc/nginx.conf` (or something like that).

This is not possible for instance

```
worker_processes auto;
worker_rlimit_nofile 2048; 
worker_connections 1024;

events {}

http { ... }
```

Is there a way I can provide such configuration and still use the `envsubst` approach?
Wouldn't be a good idea to include another `.conf` file at the global context?
i.e:
```nginx
# nginx.conf
include       /etc/nginx/default.conf;
http {
    include /etc/nginx/conf.d/*.conf;
}
```
