### ISSUE TITLE
Unable to telnet to phpfpm container

### ISSUE THREAD

**Issue by codeasashu** [nginxinc/docker-nginx#301]
I am using docker-compose.

I am using `nginx:alpine` image along with `mariadb:latest` and `php:fpm-alpine`. Both the php and mariadb are mentioned in `depends_on` parameter within `nginx` service. My docker-compose files looks like this:

```yaml
version: '3'

services:
    app:
        image: nginx:alpine
        ports:
            - 80:80
        depends_on:
            - db
            - phpfpm

    db:
        image: mariadb:latest
        ports:
            - 3306:3306
        environment:
            - "MYSQL_ROOT_PASSWORD=root"
    phpfpm:
        image: php:fpm-alpine
        expose:
            - 9000
```

When I try to execute following command in nginx container (app in this case) using:

*This doesn't work*
`docker-compose exec app telnet phpfpm 90000` 

I do not get any response. It keeps hanging there until I quit it forcefully.

However, when I do the same in `db` container, it can telnet successfully

*This works*
`docker-compose exec db telnet phpfpm 9000`

---

However, this issue is resolved when I use `nginx:latest` image, in which case, I can telnet successfully to phpfpm container.
