### ISSUE TITLE
Docker image creating directory for logs

### ISSUE THREAD

**Issue by limeandcoconut** [nginxinc/docker-nginx#323]
I'm using this docker compose:

```
version: '3.7'
services:
    auth-postgres:
        image: postgres:alpine
        container_name: auth-postgres
        restart: always
        env_file:
            - ./config/db.env
        ports:
            - 5432:5432
        volumes:
            - ./pg_data:/var/lib/postgresql/data
    session-redis:
        image: redis:alpine
        container_name: session-redis
        restart: always
        ports:
            - 6379:6379
        volumes:
            - ./redis_data:/data
    nginx: 
      image: nginx:latest
      container_name: nginx
      volumes:
        - ./config/nginx.conf:/etc/nginx/nginx.conf
        - ./error.log:/etc/nginx/error_log.log
        - ./build/client/:/etc/nginx/html/
      ports:
        - 8502:80
```

Which has been working fine on macOS mojave but when starting on Ubuntu 18.04.2 LTS I get this.

```
nginx            | 2019/04/12 18:46:09 [emerg] 1#1: open() "/etc/nginx/error_log.log" failed (21: Is a directory)
nginx            | nginx: [emerg] open() "/etc/nginx/error_log.log" failed (21: Is a directory)
```
Seems that the container is creating a directory here and doesn't like it.

`
drwxr-xr-x    2 root            root 4.0K Apr 12 18:46 error.log
`
