### ISSUE TITLE
Running container as unprivileged user not possible anymore

### ISSUE THREAD

**Issue by seagleNet** [nginxinc/docker-nginx#329]
Since commit 0501f0b73fd7fbfb139d1e98a7fd3b63426b16a1 it's not possible to run containers as an unprivileged user anymore because following lines have been removed:

```
	&& addgroup -S nginx \
	&& adduser -D -S -h /var/cache/nginx -s /sbin/nologin -G nginx nginx \
```

Run on k8s with:

```yaml
        securityContext:
          runAsUser: 100
          allowPrivilegeEscalation: false
```

Result in:

```none
2019/05/14 15:28:10 [emerg] 1#1: mkdir() "/var/cache/nginx/proxy_temp" failed (13: Permission denied)
nginx: [emerg] mkdir() "/var/cache/nginx/proxy_temp" failed (13: Permission denied)
```
