### ISSUE TITLE
Duplicate records in access.log

### ISSUE THREAD

**Issue by pbozhko** [nginxinc/docker-nginx#349]
Configs for container:

_nginx.conf_
```
events { }
http {
  server {
    location ~* {
      return 200;
    }
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log debug;
  }
}
```

_docker-compose.yml_
```
version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./logs:/var/log/nginx
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
```

Steps to reproduce:
1. For example send 15 unique requests (with 150-200 characters in url) with interval around 5 seconds.
2. Each of 15 requests is logged in access.log file with own request time.
3. Wait about 15-20 seconds
4. There are 15 same records added in the end of access.log file with modified request time field (all records have same request time)  

Repeat these steps if problem doesn't reproduce (I catch this one not always for the first time).
