### ISSUE TITLE
Nginx logging not working

### ISSUE THREAD

**Issue by gautamkrishnar** [nginxinc/docker-nginx#367]
I have the following conf file:
```
server {
    server_name domain.domain.com;
    listen 443 ssl;
    set $env "staging";
    set $project "api";
    set $public_folder "wwwdata";
    set $connect_ui_folder "connect-ui/build";
    access_log on;
    set $error_log "/var/log/shared/php-5.nginx_access.log";
    set $access_log "/var/log/shared/php-5.nginx_error.log";
    index index.php index.html;
    ssl_certificate /srv/etc/ssl/docker.cer;
    ssl_certificate_key /srv/etc/ssl/docker.key;
    error_log $error_log;
    access_log  $access_log;
    set $app_root "/srv/www/$project";
    set $app_doc_root $app_root/$public_folder;
    location / {
        try_files   $uri /index.html;
        root        /srv/www/$connect_ui_folder;
        add_header Service-Worker-Allowed /;
    }

    # API call to /api/v1/ goes to the connect-api project.
    location /api/v1/ {
    #location / {
        try_files   $uri $uri/ /index.php?$args;
        root        $app_doc_root;
        index index.php index.html;
    }
    location ~ \.php$ {
        fastcgi_param ENV $env;
        include /etc/nginx/fastcgi_params;
        fastcgi_pass php-fpm-5.docker:9000;
        fastcgi_param SCRIPT_FILENAME $app_doc_root$fastcgi_script_name;
    }
    location ~ /\.ht {
        deny all;
    }
}
```

I am not able to see the access log in /var/log/shared/php-5.nginx_access.log or error log in var/log/shared/php-5.nginx_error.log. The directory is mounted as volume to container via the following compose.yml:
```
  nginx.docker:
        image: nginx:latest
        ports:
            - "443:443"
        links:
            - php-fpm-7.docker
            - php-fpm-5.docker
            - memcached.docker
            - mongo.docker
            - redis.docker
            - mysql.docker
            - pgsql.docker
        volumes:
            - ./Workspace/etc/nginx/conf.d:/etc/nginx/conf.d
            - ./Workspace/etc/ssl:/srv/etc/ssl
            - ./Workspace/log:/var/log/shared
            - ./:/srv/www
```
