### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by bilalmalik777** [nginxinc/docker-nginx#449]
Hello guys, i have moved my applications into docker and it is running perfectly. now I want to run my application with Nginx server as a reverse proxy but getting 502 Bad Gateway. Docker-compose, Nginx, and proxy conf files are given below please help me sort out this issue
In error log it shows the following error
`2020/09/08 08:26:39 [error] 30#30: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: nginx, request: "GET /swagger HTTP/1.1", upstream: "http://172.24.0.6:5000/swagger", host: "localhost"`

**Docker-compose file**
```
version: '3.4'

services:

  nginx:
    image: nginx:alpine
    hostname: 'nginx'
    volumes:
      - ${APPDATA}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${APPDATA}/nginx/proxy.conf:/etc/nginx/proxy.conf:ro
      - ${APPDATA}/nginx/ssl/localhost.crt:/etc/ssl/certs/localhost.crt:ro
      - ${APPDATA}/nginx/ssl/localhost.key:/etc/ssl/certs/localhost.key:ro
      - ${APPDATA}/nginx/logs/:/var/log/nginx/
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - api
    restart: always
    networks:
     - app-network

  api:
    image: ${DOCKER_REGISTRY-}ttcoreapi
    build:
      context: .
      dockerfile: TT.Core.Api/Dockerfile
    restart: always
    ports:
     - '5000'
    networks:
      app-network:
        ipv4_address: 172.24.0.6

networks:
  app-network:
    ipam:
      driver: default
      config:
        - subnet: 172.24.0.0/24
```

**nginx.conf**

```
user nginx;

worker_processes    auto;

events { worker_connections 1024; }

http {
    log_format upstream_time '$remote_addr $http_x_forwarded_for - $remote_user [$time_local] '
                             '$ssl_protocol "$request" $status $body_bytes_sent '
                             '"$http_referer" "$http_user_agent"'
                             'rt=$request_time uct="$upstream_connect_time" uht="$upstream_header_time" urt="$upstream_response_time"';
    access_log /var/log/nginx/access.log upstream_time;

    include         /etc/nginx/proxy.conf;
    include         /etc/nginx/mime.types;
    limit_req_zone  $binary_remote_addr zone=one:10m rate=5r/s;
    server_tokens   off;

    sendfile on;
    keepalive_timeout   29; # Adjust to the lowest possible value that makes sense for your use case.
    client_body_timeout 10; client_header_timeout 10; send_timeout 10;

    upstream webapi {
        server api:5000;
    }

    server {
        listen     *:80 default_server;
        add_header Strict-Transport-Security max-age=15768000;
        return     301 https://$host$request_uri;
    }

    server {
        listen                      443 ssl;
        server_name                 $hostname;
        ssl_certificate             /etc/ssl/certs/localhost.crt;
        ssl_certificate_key         /etc/ssl/certs/localhost.key;
        ssl_protocols               TLSv1.1 TLSv1.2;
        ssl_prefer_server_ciphers   on;
        ssl_ciphers                 "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
        ssl_ecdh_curve              secp384r1;
        ssl_session_cache           shared:SSL:10m;
        ssl_session_tickets         off;
        # ssl_stapling                on; #ensure your cert is capable
        # ssl_stapling_verify         on; #ensure your cert is capable

        add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload" always;
        add_header X-Frame-Options DENY;
        add_header X-Content-Type-Options nosniff;
        add_header X-Frame-Options "SAMEORIGIN";

        location / {
            proxy_pass http://webapi;
            limit_req  zone=one burst=10 nodelay;
        }
    }
}
```

**proxy.conf**

```
proxy_redirect          off;
proxy_http_version      1.1;
proxy_set_header        Upgrade             $http_upgrade;
proxy_cache_bypass      $http_upgrade;
proxy_set_header        Connection          keep-alive;
proxy_set_header        Host $host;
proxy_set_header        X-Real-IP           $remote_addr;
proxy_set_header        X-Forwarded-For     $proxy_add_x_forwarded_for;
proxy_set_header        X-Forwarded-Proto   $scheme;
proxy_set_header        X-Forwarded-Host    $server_name;
client_max_body_size    10m;
client_body_buffer_size 128k;
proxy_connect_timeout   90;
proxy_send_timeout      90;
proxy_read_timeout      90;
proxy_buffers           32 4k;
```
