### ISSUE TITLE
nginx start can't get cpu limit and change worker_processes numbers

### ISSUE THREAD

**Issue by Darren-wh** [nginxinc/docker-nginx#472]
nginx start can't get cpu limit and change worker_processes numbers. 
I think you can add follow scripts to docker-entrypoint.sh.
 
```
CPU_CFS_QUOTA_US=`cat /sys/fs/cgroup/cpu,cpuacct/cpu.cfs_quota_us`
CPU_CFS_PERIOD_US=`cat /sys/fs/cgroup/cpu,cpuacct/cpu.cfs_period_us`
if [ "$CPU_CFS_PERIOD_US" -ne "-1" ]
then
WORKER_PROCESSES=`awk 'BEGIN{printf "%.2f\n",'''$CPU_CFS_QUOTA_US'''/'''$CPU_CFS_PERIOD_US'''}'|awk '{print int($1+1)}'`
sed  -i "s/worker_processes  2/worker_processes  $WORKER_PROCESSES/g" /etc/nginx/nginx.conf
fi
```

add this script,The nginx can start with the worker_processes auto.

**Comment by thresheek** [comment]
Hi @Darren-wh!

Thanks for the suggestion, this fits nicely into entrypoints IMO.

I've just pushed a branch called "tune-worker-processes" to https://github.com/nginxinc/docker-nginx/tree/tune-worker-processes - it would be nice if you can rebuild the image & check if it works for your usecase.  This tuning is not done by default, you'd need to set an environment variable `NGINX_ENTRYPOINT_WORKER_PROCESSES_AUTOTUNE` to any value to have an effect when launching a container.

Here's a list of actions needed to build & run it locally:
```
$ git clone https://github.com/nginxinc/docker-nginx
$ cd docker-nginx
$ git checkout -f tune-worker-processes
$ cd mainline/debian
$ docker build -t nginx-tuned:1.19.5 .
$ docker run -e NGINX_ENTRYPOINT_WORKER_PROCESSES_AUTOTUNE=1 -d --name nginx-tuned nginx-tuned:1.19.5
```
At this point the container named "nginx-tuned" should be running, and you can check if the limits were correctly applied via:
```
$ docker exec nginx-tuned cat /etc/nginx/nginx.conf
```
In my case it resulted in something like:
```
user  nginx;
# Commented out by 30-tune-worker-processes.sh on Tue Dec  1 14:01:33 UTC 2020
#worker_processes  1;
worker_processes 8;
...
```

**Comment by Darren-wh** [comment]
@thresheek It can get Deployment resources CPU limits and then auto to set worker_processes when starting Nginx?

**Comment by thresheek** [comment]
@Darren-wh Yes. That is also what I would like you to test. :-)

**Comment by Darren-wh** [comment]
@thresheek /:strong

**Comment by lin1005q** [comment]
Add command to a k8s pod, this script(`30-tune-worker-processes.sh`) does not work.

eg: 

```yaml
command:
- wait-for-it.sh
- server:8080
- --timeout=1
- --strict
- --
- nginx
- -g
- daemon off;
env:
- name: NGINX_ENTRYPOINT_WORKER_PROCESSES_AUTOTUNE
  value: "1"
```

**Comment by Darren-wh** [comment]
@lin1005q What request and limit resources of Kubernetes do you set? If you add 
 env NGINX_ENTRYPOINT_WORKER_PROCESSES_AUTOTUNE, you must set the request and limit resources of Kubernetes.

**Comment by lin1005q** [comment]
Thanks!!!   The following are the steps to reproduce.

### download wait-for-it.sh

[wait-for-it.sh.zip](https://github.com/nginxinc/docker-nginx/files/7074086/wait-for-it.sh.zip)

And unzip it

### docker build -t nginx-test .


```
FROM nginx:alpine
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories
RUN apk add --no-cache bash coreutils
ADD $PWD/wait-for-it.sh /usr/local/bin/wait-for-it.sh
RUN chmod +x /usr/local/bin/wait-for-it.sh
```

### kubectl apply -f nginx-test.yaml

**replace 192.168.10.6:443 to another port**

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-test
    spec:
      containers:
      - command:
        - wait-for-it.sh
        - 192.168.10.6:443
        - --timeout=1
        - --strict
        - --
        - nginx
        - -g
        - daemon off;
        env:
        - name: NGINX_ENTRYPOINT_WORKER_PROCESSES_AUTOTUNE
          value: "1"
        image: nginx-test
        imagePullPolicy: Never
        name: nginx-test
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 1000m
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 100Mi
```

```bash
[root@192-168-50-90 nginx-test]# kubectl exec -it -n default nginx-test-b84867d5-fmmj9 -- ps -ef
PID   USER     TIME  COMMAND
    1 root      0:00 nginx: master process nginx -g daemon off;
   19 nginx     0:00 nginx: worker process
   20 nginx     0:00 nginx: worker process
   21 nginx     0:00 nginx: worker process
   22 nginx     0:00 nginx: worker process
   23 nginx     0:00 nginx: worker process
   24 nginx     0:00 nginx: worker process
   25 nginx     0:00 nginx: worker process
   26 nginx     0:00 nginx: worker process
   27 nginx     0:00 nginx: worker process
   28 nginx     0:00 nginx: worker process
   29 nginx     0:00 nginx: worker process
   30 nginx     0:00 nginx: worker process
   31 nginx     0:00 nginx: worker process
   32 nginx     0:00 nginx: worker process
   33 nginx     0:00 nginx: worker process
   34 nginx     0:00 nginx: worker process
   43 root      0:00 ps -ef
```

### delete command && kubectl apply -f 

```bash
[root@192-168-50-90 nginx-test]# kubectl exec -it -n default nginx-test-79f49f8847-nxgtv -- ps -ef
PID   USER     TIME  COMMAND
    1 root      0:00 nginx: master process nginx -g daemon off;
   97 nginx     0:00 nginx: worker process
   98 root      0:00 ps -ef
```
