### ISSUE TITLE
nginix 1.19.6 fails vulnerability scan due to CVE-2020-29363

### ISSUE THREAD

**Issue by alfonsoar** [nginxinc/docker-nginx#503]
Hi  - not sure if this is the right repo to report this but since this morning we started seeing some failures since the `nginix` images are failing vulnerability scans due to `CVE-2020-29363`

```yaml
Analysing 7 layers
 Unknown: 3
 Negligible: 57
 Low: 20
 Medium: 28
 High: 1
 CVE-2020-29363: [High] 
 Found in: p11-kit [0.23.15-2]
 Fixed By: 
 An issue was discovered in p11-kit 0.23.6 through 0.23.21. A heap-based buffer overflow has been discovered in the RPC protocol used by p11-kit server/remote commands and the client library. When the remote entity supplies a serialized byte array in a CK_ATTRIBUTE, the receiving entity may not allocate sufficient length for the buffer to store the deserialized value.
 https://security-tracker.debian.org/tracker/CVE-2020-29363
```
