### ISSUE TITLE
SUPPORT - Deploy Bootstrap template with Ngnix via Docker Compose

### ISSUE THREAD

**Issue by ansred** [nginxinc/docker-nginx#521]
Greetings,

I have the setup working, but for some reason, it's not able to show the static page mounted, and instead, it shows the default nginx page.

Here is the stack I used

```
web:
  image: nginx
  container_name: lab-redmedia-bootstrap
  volumes:
   - /volume1/docker/Bootstrap/redrice/:/usr/local/nginx/html:ro
  ports:
   - "8228:80"
```

Stack was deployed via Portainer on Synology NAS and It's running 

![image](https://user-images.githubusercontent.com/5244872/111301697-e42e8580-8628-11eb-9430-901fa0cd6f75.png)

the issue is, when I access the URL, it shows the default nginx page, not the static page mounted in the v path

![image](https://user-images.githubusercontent.com/5244872/111301854-117b3380-8629-11eb-9d1d-3d1a56efd677.png)

Even though the container inspect shows it's correctly mounted/mapped

![image](https://user-images.githubusercontent.com/5244872/111301985-37a0d380-8629-11eb-88ab-4ac45e62360a.png)

and here is the directory that has the files

![image](https://user-images.githubusercontent.com/5244872/111302077-543d0b80-8629-11eb-8777-05acf0f83cec.png)

Any idea what the issue might be?

**Comment by thresheek** [comment]
Hi @ansred!

Please check https://hub.docker.com/_/nginx section "Hosting some simple static content".

Seems like you have a wrong path in your docker-compose volume.

**Comment by ansred** [comment]
What do you think the issue in the path? 
As you can see I have mapped the volume to the directory that has the files of the bootstrap website.

Do I need to include the index.html file name in the path?

I tried that and it didn't help

**Comment by thresheek** [comment]
the default configuration in the image expects `/usr/share/nginx/html`, not `/usr/local/nginx/html`

**Comment by ansred** [comment]
> the default configuration in the image expects `/usr/share/nginx/html`, not `/usr/local/nginx/html`

You were right! not sure where I got that from the local instead of share.

It worked like a charm now

```
web:
  image: nginx
  container_name: lab-redmedia-bootstrap
  volumes:
   - /volume1/docker/Bootstrap/redrice/:/usr/share/nginx/html
  ports:
   - "8228:80"
```

Thank you!!
