### ISSUE TITLE
mkdir() "/var/cache/nginx/client_temp" failed (13: Permission denied)

### ISSUE THREAD

**Issue by lbopp42** [nginxinc/docker-nginx#524]
Hello,
I'm using the image **nginx:alpine** and sometime for the fist **docker-compose up -d** I got this error spammed in logs:

`mkdir() "/var/cache/nginx/client_temp" failed (13: Permission denied)`

If I **docker-compose up -d** again my container it will be fixed but why ?

Best regards,
Lucas BOPP

**Comment by thresheek** [comment]
Hi @lbopp42, can you show the full configuration you're using?  All the docker-compose configs, and nginx ones.

Thanks,

**Comment by lbopp42** [comment]
Hi thanks for your time.
I'm using the default conf of nginx:alpine and this is a part of docker-compose
```
  my_service: (edit)
    cap_add:
    - CAP_CHOWN
    - CAP_NET_BIND_SERVICE
    - CAP_SETGID
    - CAP_SETUID
    cap_drop:
    - ALL
    depends_on:
    - app_back (edit)
    env_file:
    - .env
    image: myimage_name (edit)
    labels:
       some_labels_for_traefik (edit)
    networks:
    - default
    - traefik
    restart: always
    ```
    Do this help you ?

**Comment by thresheek** [comment]
Not really, I cant reproduce with the following `docker-compose.yml`:
```
my_service:
  cap_add:
  - CAP_CHOWN
  - CAP_NET_BIND_SERVICE
  - CAP_SETGID
  - CAP_SETUID
  cap_drop:
  - ALL
  image: nginx:alpine
  restart: always
```

Are there any changes you're doing to `nginx:alpine` image?  I notice you have `myimage_name` instead.
