### ISSUE TITLE
Building nginx with extra module breaks because of setfattr

### ISSUE THREAD

**Issue by Monokai** [nginxinc/docker-nginx#525]
Following the [instructions](https://github.com/nginxinc/docker-nginx/tree/master/modules) of building nginx with extra modules, I'm including the `geoip2` module. I'm using the Alpine version.

This all works fine locally, but when building the same Dockerfile in a Gitlab CI setup, it breaks.

I've narrowed it down to this step:

```
>>> nginx-module-geoip2-dbg: Running split function dbg...
setfattr: ngx_http_geoip2_module-debug.so: Not supported
>>> ERROR: nginx-module-geoip2-dbg: dbg failed
>>> ERROR: nginx-module-geoip2: prepare_subpackages failed
>>> ERROR: nginx-module-geoip2: rootpkg failed
```

Seems [abuild](https://github.com/alpinelinux/abuild/blob/master/abuild.in) uses `setfattr`, which isn't supported on every environment by the looks of this error.

Any ideas on how to fix this?

**Comment by thresheek** [comment]
Hi @Monokai!

How do you run the Gitlab CI runner, is it under your control?  If no, I dont think there is anything we can do except file a FR for `abuild` to skip the getfattr/setfattr calls if not supported.  If you do have control, can you share the `config.toml` of a runner so I can try and reproduce?

Thanks!

**Comment by Monokai** [comment]
Thank for your quick reply.

I'm using a shared runner and the relevant part of `gitlab-ci.yml` is this:

```yaml
stages:
  - build
  - deploy

.docker: &docker
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

.build-nginx:
  <<: [*docker]
  stage: build
  variables:
    IMAGE: "${CI_REGISTRY_IMAGE}:nginx-${CI_COMMIT_REF_SLUG}"
  script:
    - docker pull $IMAGE-latest || true

    - >
      docker build
      --build-arg ENABLED_MODULES=geoip2
      --cache-from $IMAGE-latest
      --tag $IMAGE
      --tag $IMAGE-latest
      --file ./components/nginx/build/Dockerfile .

    - docker push $IMAGE
    - docker push $IMAGE-latest
```
