### ISSUE TITLE
"docker logs" command outputs nothing

### ISSUE THREAD

**Issue by tian-yan** [nginxinc/docker-nginx#537]
I am setting up a NGINX node as container using image 1.19.10-alpine.
my docker compose file is as below:
```
version: '3.9'

services:
  reverse_proxy_nginx:
    image: nginx:1.19.10-alpine
    container_name: reverse_proxy_nginx

    networks:
      external_net:
        ipv4_address: 192.168.100.10
    ports:
      - "80:80"

    volumes:    
      - ./static/:/usr/share/nginx/html/
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/localtime:/etc/localtime:ro

    command: sh -c "rm -f /etc/nginx/conf.d/* &&
      nginx -c /etc/nginx/nginx.conf"
       
    tty: true


networks:
  external_net:
    external:
      name: localsw
```
after docker-compose up command:
```
[root@Site Reverse_Proxy]# docker ps -a
CONTAINER ID   IMAGE                         COMMAND                  CREATED         STATUS                      PORTS                 NAMES
e1498798339d   nginx:1.19.10-alpine          "/docker-entrypoint.…"   6 seconds ago   **Exited (0) 5 seconds ago**                          reverse_proxy_nginx
```

"docker logs" command and containerID-json.log all output nothing !
```
[root@Site Reverse_Proxy]# docker logs reverse_proxy_nginx 
[root@Site Reverse_Proxy]# cat /var/lib/docker/containers/e1498798339d022ec5d744e1c557ca3e9f0779be114ffb0349acc9be1a70e5c7/e1498798339d022ec5d744e1c557ca3e9f0779be114ffb0349acc9be1a70e5c7-json.log 
[root@Site Reverse_Proxy]# 
```
In my previous attempts, I did see "docker logs" output logs showing executing docker-entrypoint.sh and other shell scripts (10-listen-on-ipv6-by-default.sh, 20-envsubst-on-templates.sh etc), also looking for default.conf file to initialize NGINX server. but now, it outputs nothing !!

I searched quite a long time on this issue, and did not find any solid & holistic solution yet. not sure whether issue resides on the image itself, or it is a bug of docker technology, or I did something incorrectly.
