### ISSUE TITLE
Docker Compose - Version 3 - Nginx with Static Website Page

### ISSUE THREAD

**Issue by ansred** [nginxinc/docker-nginx#544]
**Subject:**
Docker Compose - Version 3 - Nginx with Static Website Page

**Issue:**
Trying to shape the docker compose version 3 to use

**Setup:**
Docker on Synology NAS
Portainer as Docker GUI

**Details:**
I have the following stack that is working without issues:

```
web:
  image: nginx
  container_name: lab-redmedia-bootstrap
  volumes:
   - /volume1/docker/Bootstrap/redrice/:/usr/share/nginx/html:ro
  ports:
   - "8228:80"
```

However, I am trying to add the extra part to connect with another container and use its network

`    network_mode: "container:gluetun-Mullvad"`

Can someone help me please with the shaping/correcting the docker compose to make it work?

Thanks!

**Comment by ansred** [comment]
Managed to get it working by combining both containers in the same stack 


Here for the ref:


```

################################################################################################
version: "3.7"
services: 
  gluetun-Mullvad: 
    cap_add: 
      - NET_ADMIN
    container_name: gluetun-Mullvad
    environment: 
      - PUID=1029
      - PGID=100
      - TZ=America/Toronto
      - VPNSP=mullvad
      - PORT=443
      - COUNTRY=Canada
      - CITY=Montreal
      - PORT_FORWARDING=on
      - PORT_FORWARDING_STATUS_FILE=/gluetun/port-forwarding/port.conf
      - OPENVPN_USER=$$$$$$$$$$$$$ #Change to YOUR Username"
      - FIREWALL_VPN_INPUT_PORTS=55939 #ca-mtr-55939 PORT MULLVAD
      - PROTOCOL=tcp
      - OPENVPN_IPV6=off
    image: qmcgaw/gluetun
    ports: 
      - "8002:8000" #HTTP Server https://github.com/qdm12/gluetun/wiki/HTTP-Control-server#OpenVPN
      - "8228:80" #lab-ansred-bootstrap and the forwared port
    volumes: 
      - "/volume1/docker/gluetun/gluetun-Mullvad/config:/gluetun"
################################################################################################
  web: 
    container_name: lab-redmedia-bootstrap
    image: nginx
    network_mode: "service:gluetun-Mullvad"
    volumes: 
      - "/volume1/docker/Bootstrap/redrice/:/usr/share/nginx/html:ro"
################################################################################################
```
