### ISSUE TITLE
unknown directive proxy_pass

### ISSUE THREAD

**Issue by lvturner** [nginxinc/docker-nginx#569]
Hi, I'm trying to set up a reverse proxy using docker compose to other docker containers, but no matter what I try it fails and I get the error message below

```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/default.conf.template to /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/default.conf.template to /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2021/08/21 08:22:14 [emerg] 1#1: unknown directive "proxy_pass:" in /etc/nginx/conf.d/default.conf:5
nginx: [emerg] unknown directive "proxy_pass:" in /etc/nginx/conf.d/default.conf:5
2021/08/21 08:22:14 [emerg] 1#1: unknown directive "proxy_pass:" in /etc/nginx/conf.d/default.conf:5
nginx: [emerg] unknown directive "proxy_pass:" in /etc/nginx/conf.d/default.conf:5
```

my docker-compose.yml is as follows

```
version: "3.9"
services:
        grafana:
                image: "grafana/grafana:latest"
                hostname: grafana
                restart: "always"
                ports:
                    - "3000:3000"
        postgres:
                image: "postgres:latest"
                hostname: postgres
                restart: "always"
                environment:
                    POSTGRES_PASSWORD: personal_health
                ports:
                    - "5432:5432"
                volumes:
                    - ./data:/var/lib/postgresql/data
        adminer:
                image: adminer
                hostname: adminer
                restart: "always"
                ports:
                    - "8080:8080"
        web:
                build: ./nginx
                ports:
                    - "88:80"
                environment:
                    - NGINX_PORT=80

```                    

and in my nginx-tempaltes folder, I have default.conf.template, which is as follows

```
server {
    listen ${NGINX_PORT};

    location / {
        proxy_pass: http://grafana:3000/;
    }
}

```

Any suggestions would be greatly appreciated
