### ISSUE TITLE
NGINX can't find files that exist

### ISSUE THREAD

**Issue by MaximumMaxxx** [nginxinc/docker-nginx#636]
So I'm working on adding SSL to a little reverse proxy I have running in a docker container. however I keep running into this error 

`nginx: [emerg] cannot load certificate "/var/cert/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/var/cert/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)`

Here's my domain conf file
```
server {
     listen 80;
     listen [::]:80;
     server_name laurel.community www.laurel.community;

     listen 443 ssl; # managed by Certbot

     ssl_certificate "/var/cert/fullchain.pem";
     ssl_certificate_key "/var/cert/privkey.pem";

     include "/var/cert/nginx.conf";

     root /var/www/laurel.community;

     index index.html index.htm;

     if ($scheme != "https") {
          return 301 https://$host$request_uri;
     }

     location / {
          try_files $uri $uri/ =404;
     }
}
```

My docker compose file
```yaml
services:
  reverse:
    restart: always
    container_name: reverse
    hostname: reverse
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/maximummaxx/Documents/DOCKERuments/NGINX/Conf:/etc/nginx
      - /home/maximummaxx/Documents/DOCKERuments/NGINX/www:/var/www/
      - /etc/letsencrypt/live/laurel.community/:/var/cert
```

and proof that the files exist in the directory
<img src="https://cdn.discordapp.com/attachments/948461782937247764/948741712732381204/unknown.png">
