### ISSUE TITLE
Unable to start container with mounted /etc/nginx/nginx.conf

### ISSUE THREAD

**Issue by dosera** [nginxinc/docker-nginx#650]
Hi,

after pulling the most recent image starting the container is no longer possible due to an error with `sed`:

```
sed: cannot rename /etc/nginx/nginx.conf: Device or resource busy
```
This seems to have been introduced with https://github.com/coreruleset/modsecurity-docker/pull/105.
In my setup I mount the `nginx.conf` from my host into the container - which is incompatible with the `sed` renaming (cf. https://github.com/coreruleset/modsecurity-docker/blob/master/v3-nginx/docker-entrypoint.d/91-update-resolver.sh @ line 12)

Minimal compose:

```
version: "3"
services:
  nginx:
    image: owasp/modsecurity:nginx
    restart: always
    volumes:
      - /host/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
```

I am actually unsure on whether this should be *used* differently - yet at least on the nginx dockerhub there are many references wrt. mounting the `nginx.conf` from the host (see https://hub.docker.com/_/nginx) into the container.
