### ISSUE TITLE
Getting different results when pinging vs nslookup on Kubernetes from inside nginx.

### ISSUE THREAD

**Issue by Slyke** [nginxinc/docker-nginx#658]
This started after I rebooted my cluster about a week ago. It's rebooted on the first of each month. I have a nginx reverse proxy setup and have started to see weird issues and 50X errors being returned. I exec'd into the nginx pod and ran the following commands:
```
/ # ping motioneye.home.svc.cluster.local
PING motioneye.home.svc.cluster.local (10.7.9.10): 56 data bytes
^C
--- motioneye.home.svc.cluster.local ping statistics ---
4 packets transmitted, 0 packets received, 100% packet loss
/ # cat /etc/resolv.conf
nameserver 10.96.0.10
search injester.svc.cluster.local svc.cluster.local cluster.local phoxis.xyz
options ndots:5
/ # nslookup motioneye.home.svc.cluster.local
Server:         10.96.0.10
Address:        10.96.0.10:53


Name:   motioneye.home.svc.cluster.local
Address: 10.105.38.36
```

The correct IP is 10.105.38.36, but both ping and the nginx process are both getting 10.7.9.10 which is the LAN IP of my Ingress controller pod ( https://github.com/kubernetes/ingress-nginx ). This is an issue because `proxy_pass` is also resolving to the same incorrect IP as ping.

Here's the service for motioneye:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: motioneye
  name: motioneye
  namespace: home
spec:
  externalTrafficPolicy: Local
  ports:
  - name: motioneye-http
    protocol: TCP
    port: 8765
  - name: motioneye-http2
    protocol: TCP
    port: 80
    targetPort: 8765
  selector:
    app: motioneye
```

And here's the deployment for my nginx reverse proxy:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-rp
  name: nginx-rp
  namespace: injester
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: nginx-rp
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-rp
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: nginx-rp
      containers:
      - env:
        - name: ServerIP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: nginx:1.21-alpine
        imagePullPolicy: IfNotPresent
        name: nginx-rp
        livenessProbe:
          httpGet:
            path: /health
            port: 80
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            memory: "2Gi"
            cpu: "1"
        ports:
        - containerPort: 80
          name: nginx-http
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: nginx-data
        - mountPath: /etc/nginx/certs
          name: nginx-certs
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nginx-data
        persistentVolumeClaim:
          claimName: nginx-injester-conf-claim
      - name: nginx-certs
        persistentVolumeClaim:
          claimName: nginx-injester-certs-claim
      - name: nginx-config
        configMap:
          name: nginx-config-cm
status: {}
```

In my default.conf I've tried adding:
```
server {
  listen 80 default_server;
  listen [::]:80 default_server;
  resolver 10.96.0.10 valid=10s;
```

But no success
