### ISSUE TITLE
Mount script into docker-entrypoint.d

### ISSUE THREAD

**Issue by bozo-david-allwin** [nginxinc/docker-nginx#688]
I want to add an init script without modifying the entrypoint in my docker compose. I use volumes to mount my script into docker-entrypoint.d but it fails.

docker-compose.yml
``` yml
  nginx:
    container_name: nginx
    image: nginx:1.23-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Nginx/nginx-init.sh:/docker-entrypoint.d/100-nginx-init.sh
      - ./Nginx/someapp.localtest.me.conf:/etc/nginx/sites-available/someapp.localtest.me.conf
      - ./Nginx/calculation.someapp.localtest.me.conf:/etc/nginx/sites-available/calculation.someapp.localtest.me.conf
      - ./Nginx/certs/someapp.localtest.me.pem:/etc/nginx/ssl/someapp.localtest.me.pem
      - ./Nginx/certs/someapp.localtest.me.key:/etc/nginx/ssl/someapp.localtest.me.key
    depends_on:
      - someapp.api
      - someapp.calculation.api
```

container logs:
``` console
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/100-nginx-init.sh
/docker-entrypoint.sh: line 22: /docker-entrypoint.d/100-nginx-init.sh: not found
```

I'm confused. It tries to launch there for it is there but not found if it tries to run. I checked into the container it looked like my script has run permission.
