### ISSUE TITLE
Alpine tag configuration discrepancy

### ISSUE THREAD

**Issue by jrarseneau** [nginxinc/docker-nginx#74]
Hello,

Was starting to fiddle with the :alpine tag tonight, here's my docker-compose.yml that's been working fine for months:

```
nginx:
    image: nginx
    hostname: nginx
    restart: always
    ports:
        - "80:80"
    volumes:
        - ~/sites/my-site.conf:/etc/nginx/conf.d/default.conf:ro
        - ~/sites/my-site.com:/var/www/my-site.com
```

Adding the `alpine` tag to that compose file breaks the container and all requests go to the default pages in `/etc/nginx/html`

I can get around this if I set the volume location of `~/sites/my-site.com:/etc/nginx/html` however, it doesn't appear that nginx is correctly loading the `my-site.conf` file I've placed in the folder.

The nginx page on docker hub does not make any references to having to change any configuration. So my question: is this intended? If not, then I believe it should work the same as baseline `nginx` or if it is intended, then that should be documented on docker hub.

Thanks,
