### ISSUE TITLE
PHP-FPM not accessible in current docker image. 

### ISSUE THREAD

**Issue by RileyMeta** [nginxinc/docker-nginx#822]
Hi all,  

I've been tinkering with a Docker stack that runs; `Nginx`, `MariaDB` and `phpMyAdmin`, with mild levels of success. The web server runs and resolves properly, I can access phpMyAdmin and MariaDB, the only issue I seem to have is, regardless of what I do, I cannot get the Nginx docker to enable, start, or even acknowledge PHP-FPM. Below is my current Docker-Compose file 

```yml
version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - nginx_html:/usr/share/nginx/html
    depends_on:
      - phpmyadmin

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_DATABASE: your_mysql_database
      MYSQL_USER: your_mysql_user
      MYSQL_PASSWORD: your_mysql_user_password
    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_USER: your_mysql_user
      PMA_PASSWORD: your_mysql_user_password
    ports:
      - "8081:80"
    depends_on:
      - mariadb

volumes:
  mariadb_data:
  nginx_conf:
  nginx_html:
  ```
I've also attempted to add an additional `depends_on` clause with php-fpm, manually going into the docker shell and installing the latest release of php-fpm, installing an additional docker container with just php-fpm installed and still have no access to functional PHP pages. 

Even a simple 
```php
<?php
echo "Hello World"
?>
``` 
doesn't show anything. 

  Is this a known issue or is this something I am doing wrong? I've trolled through both the Nginx FAQ, the Ubuntu forums and even a Fair few pages of Trouble shooting with ChatGPT and still haven't had any success. The closest I've been able to get is the PHP file downloading or Nginx resolving to the `50x.html` page.

**Comment by yosifkit** [comment]
😕❓ I don't see a `php:fpm` container defined in the `docker-compose.yml`. Perhaps the [`php:fpm` section](https://github.com/docker-library/docs/tree/49ae19ff9c0b28154e58ac66d8241040ce949f5e/php#phpversion-fpm) from the `php` image description will help out?  There are a few links there about configuring `php:fpm` and `nginx` containers to work together (and copied below).

>- [simplified example by @md5](https://gist.github.com/md5/d9206eacb5a0ff5d6be0)
>- [very detailed article by Pascal Landau](https://www.pascallandau.com/blog/php-php-fpm-and-nginx-on-docker-in-windows-10/)
>- [Stack Overflow discussion](https://stackoverflow.com/q/29905953/433558)

**Comment by RileyMeta** [comment]
I took it out of that yml file, so I understand the confusion. 
  I basically had it like this: 
```yml
 depends_on:
      - php-fpm
      - phpmyadmin

  php-fpm:
    image: bitnami/php-fpm
    container_name: php-fpm
    restart: always
      - nginx_html:/var/www/html
    restart: always      
```

My Nginx config was as follows: 
```conf
server {
    listen 80;
    server_name localhost;

    root /var/www/html;
    index index.php index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ \.php$ {
        fastcgi_pass php-fpm:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.ht {
        deny all;
    }
}
```

Regardless of how I had this setup it seemed to default to the php-fpm service being disabled, not installed, or installed as it's own docker and not able to stay online for more than a single second. 

Thank you for sharing these links with me, I'll look through them and see if I can get something working.
