### ISSUE TITLE
unknown directive "auth_request" in /etc/nginx/conf.d/edgex-default.conf:59

### ISSUE THREAD

**Issue by divyashree123456** [nginxinc/docker-nginx#891]
while running nginx with docker i m facing error **nginx: [emerg] unknown directive "auth_request" in /etc/nginx/conf.d/edgex-default.conf:59**
while using edgex napa version application 
please help me to debug the issue.

**Comment by divyashree123456** [comment]
Hi @oxpa 
please find a attached docker file and compose config
[Dockerfile.txt](https://github.com/nginxinc/docker-nginx/files/15349514/Dockerfile.txt) using in riscv machine.

compose config for nginx:

```
nginx:
    command:
    - /docker-entrypoint.sh
    - nginx
    - -g
    - daemon off;
    container_name: edgex-nginx
    depends_on:
      security-secretstore-setup:
        condition: service_started
    entrypoint:
    - /bin/sh
    - /edgex-init/nginx_wait_install.sh
    environment:
      PROXY_SETUP_HOST: edgex-security-proxy-setup
      STAGEGATE_BOOTSTRAPPER_HOST: edgex-security-bootstrapper
      STAGEGATE_BOOTSTRAPPER_STARTPORT: "54321"
      STAGEGATE_DATABASE_HOST: edgex-redis
      STAGEGATE_DATABASE_PORT: "6379"
      STAGEGATE_DATABASE_READYPORT: "6379"
      STAGEGATE_PROXYSETUP_READYPORT: "54325"
      STAGEGATE_READY_TORUNPORT: "54329"
      STAGEGATE_REGISTRY_HOST: edgex-core-consul
      STAGEGATE_REGISTRY_PORT: "8500"
      STAGEGATE_REGISTRY_READYPORT: "54324"
      STAGEGATE_SECRETSTORESETUP_HOST: edgex-security-secretstore-setup
      STAGEGATE_SECRETSTORESETUP_TOKENS_READYPORT: "54322"
      STAGEGATE_WAITFOR_TIMEOUT: 60s
    hostname: edgex-nginx
    image: nginx:1.25.3-alpine-slim
    networks:
      edgex-network: {}
    ports:
    #- mode: ingress
     - 127.0.0.1:8443:8443/tcp
    read_only: true
    restart: always
    security_opt:
    - no-new-privileges:true
    tmpfs:
    - /etc/nginx/conf.d
    - /var/cache/nginx
    - /var/log/nginx
    - /var/run
    volumes:
    - edgex-init:/edgex-init:ro,z
    - nginx-templates:/etc/nginx/templates
    - nginx-tls:/etc/ssl/nginx

########################################
```

**Comment by oxpa** [comment]
Can you run 'nginx -V' in the container that fails to start and post the output here, please?
We build nginx with auth_request module so my main guess is that you are trying to use some other nginx build.
Or maybe the 'auth_request' line has some non-ascii characters in it and you have to retype it to make sure symbols match what nginx expects.

**Comment by divyashree123456** [comment]
Hi @oxpa ,
**I tried running nginx -V in compose file the following was a output:**

![Screenshot from 2024-05-23 11-08-35](https://github.com/nginxinc/docker-nginx/assets/120623642/138a0914-977b-47db-bf82-6aed4fa59f69)

**the compose file is :**

```
nginx:
    command:
    - /docker-entrypoint.sh
    - nginx
    - -V
    container_name: edgex-nginx
    depends_on:
      security-secretstore-setup:
        condition: service_started
    entrypoint:
    - /bin/sh
    - /edgex-init/nginx_wait_install.sh
    environment:
      PROXY_SETUP_HOST: edgex-security-proxy-setup
      STAGEGATE_BOOTSTRAPPER_HOST: edgex-security-bootstrapper
      STAGEGATE_BOOTSTRAPPER_STARTPORT: "54321"
      STAGEGATE_DATABASE_HOST: edgex-redis
      STAGEGATE_DATABASE_PORT: "6379"
      STAGEGATE_DATABASE_READYPORT: "6379"
      STAGEGATE_PROXYSETUP_READYPORT: "54325"
      STAGEGATE_READY_TORUNPORT: "54329"
      STAGEGATE_REGISTRY_HOST: edgex-core-consul
      STAGEGATE_REGISTRY_PORT: "8500"
      STAGEGATE_REGISTRY_READYPORT: "54324"
      STAGEGATE_SECRETSTORESETUP_HOST: edgex-security-secretstore-setup
      STAGEGATE_SECRETSTORESETUP_TOKENS_READYPORT: "54322"
      STAGEGATE_WAITFOR_TIMEOUT: 60s
    hostname: edgex-nginx
    image: nginx:1.25.3-alpine-slim
    networks:
      edgex-network: {}
    ports:
    #- mode: ingress
     - 127.0.0.1:8443:8443/tcp
    read_only: true
    restart: always
    security_opt:
    - no-new-privileges:true
    tmpfs:
    - /etc/nginx/conf.d
    - /var/cache/nginx
    - /var/log/nginx
    - /var/run
    volumes:
    - edgex-init:/edgex-init:ro,z
    - nginx-templates:/etc/nginx/templates
    - nginx-tls:/etc/ssl/nginx
```
